#spring:
#   datasource:
#       username: root
#       password: password
#       url: jbdc:mysql://localhost:3306/minijavaproject
#       driver-class-name: com.mysql.cj.jbdc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties.hiberate.dialect: org.hibernate.dialect.MySQL5Dialect